name: BuildTest

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  pull_request:
  push:
    branches:
      - master
jobs:
  job1:
    name: BuildTest
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        rosdistro: [melodic]
    env:
      ROS_DISTRO: ${{ matrix.rosdistro }}
    container: hrjp/ros:${{ matrix.rosdistro }}_cudagl
    steps:
      - uses: actions/checkout@v2
      - name: Copy repository
        run: cp -rp /__w/dynamixel_wrapper/dynamixel_wrapper /home/catkin_ws/src

      - name: Resolve rosdep
        run: |
          cd /home/catkin_ws
          apt update
          rosdep update
          rosdep install -iry --from-paths src --rosdistro ${{ matrix.rosdistro }}
      - name: Build packages
        run: |
          cd /home/catkin_ws
          catkin build